name: spack

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: checkout spack
      uses: actions/checkout@v4
      with:
        repository: spack/spack
        path: ./spack
    - name: install iowarp
      run: |
        . ./spack/share/spack/setup-env.sh
        spack external find
        spack repo add iowarp-spack
        spack install iowarp
        spack load iowarp
